---
# - name: Install httpd-tools for htpasswd utility
#   package:
#     name: httpd-tools
#     state: present
#   delegate_to: localhost
#   become: yes
- name: Install htpasswd utility on Linux and macOS
  block:
    - name: Install htpasswd on RedHat/CentOS/Fedora
      package:
        name: httpd-tools
        state: present
      when: ansible_os_family in ['RedHat', 'Rocky', 'AlmaLinux', 'Fedora']
      become: yes
      delegate_to: localhost

    - name: Install htpasswd on Debian/Ubuntu
      package:
        name: apache2-utils
        state: present
      when: ansible_os_family == 'Debian'
      become: yes
      delegate_to: localhost

    - name: Install htpasswd on macOS (via Homebrew)
      homebrew:
        name: httpd
        state: present
      when: ansible_os_family == 'Darwin'
      delegate_to: localhost

- name: Create htpasswd file with first user
  shell: |
    htpasswd -c -B -b {{ htpasswd_file }} {{ normalized_users[0].name }} {{ normalized_users[0].password }}
  delegate_to: localhost
  no_log: true

- name: Add remaining users to htpasswd file
  shell: |
    htpasswd -B -b {{ htpasswd_file }} {{ item.name }} {{ item.password }}
  loop: "{{ normalized_users[1:] }}"
  delegate_to: localhost
  no_log: true
  when: normalized_users | length > 1

- name: Create or update htpasswd secret in OpenShift
  environment:
    KUBECONFIG: "{{ cluster_data_dir }}/install-dir/auth/kubeconfig"  
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ htpasswd_secret_name }}"
        namespace: openshift-config
      type: Opaque
      data:
        htpasswd: "{{ lookup('file', htpasswd_file) | b64encode }}"
