- name: Start master nodes
  kubevirt.core.kubevirt_vm:
    name: "{{ item.name }}.{{ config.cluster_name }}.{{ config.base_domain }}"
    namespace: "{{ project_name }}"
    running: true
    kubeconfig: "{{ cluster_data_dir }}/install-dir/ovirt-kubeconfig"
  loop: "{{ masters }}"

- name: Start worker nodes
  kubevirt.core.kubevirt_vm:
    name: "{{ item.name }}.{{ config.cluster_name }}.{{ config.base_domain }}"
    namespace: "{{ project_name }}"
    running: true
    kubeconfig: "{{ cluster_data_dir }}/install-dir/ovirt-kubeconfig"
  loop: "{{ workers }}"

- name: Start infra nodes
  kubevirt.core.kubevirt_vm:
    name: "{{ item.name }}.{{ config.cluster_name }}.{{ config.base_domain }}"
    namespace: "{{ project_name }}"
    running: true
    kubeconfig: "{{ cluster_data_dir }}/install-dir/ovirt-kubeconfig"
  loop: "{{ infras }}"

  