---
- name: Validate configuration
  include_tasks: validate-config.yaml

- name: Setup directories and cleanup
  include_tasks: setup-directories.yaml

- name: Setup SSH keys
  include_tasks: setup-ssh.yaml

- name: Install required packages
  include_tasks: install-packages.yaml

- name: Download OpenShift binaries
  include_tasks: download-binaries.yaml

- name: Connect to oVirt cluster
  include_tasks: connect-ovirt.yaml
  when: ovirt is defined
