- name: Wait for bootstrap to complete prior to starting workers
  command: "{{ playbook_dir }}/bin/openshift-install --dir={{ playbook_dir }}/install-dir agent wait-for bootstrap-complete --log-level debug" # noqa 301
  retries: 180
  delay: 10
  register: result_bootstrap
  until: result_bootstrap.rc == 0

- name: Setup Infra nodes
  when: nodes.infra is defined and nodes.infra | length > 0
  block:
    - name: Check for infra nodes and label accordingly
      environment:
       KUBECONFIG: "{{ playbook_dir }}/install-dir/auth/kubeconfig"
      k8s:
       state: patched
       merge_type: merge
       definition:
         apiVersion: v1
         kind: Node
         metadata:
           name: "{{ item.name }}.{{ cluster }}.{{ config.base_domain }}"
           labels:
             node-role.kubernetes.io/infra: ""
      loop: "{{ nodes.infra }}"
    
    - name: Change ingress controller node selector
      environment:
       KUBECONFIG: "{{ playbook_dir }}/install-dir/auth/kubeconfig"
      k8s:
       state: patched
       merge_type: merge
       definition:
         apiVersion: "operator.openshift.io/v1"
         kind: IngressController
         metadata:
           name: default
           namespace: openshift-ingress-operator
         spec:
          nodePlacement:
            nodeSelector:
              matchLabels:
                node-role.kubernetes.io/infra: ""

- name: Wait for install complete
  command: openshift-install agent wait-for install-complete --dir={{ playbook_dir }}/install-dir --log-level debug # noqa 301
  register: result_complete
  until: result_complete.rc == 0
  retries: 3
  delay: 5

- name: Output results from openshift-install wait-for install-complete
  debug:
   msg: "{{ result_complete.stderr | regex_findall('level=info.*') | list }}"